### PR TITLE
Use `pip check`

### PR DESCRIPTION
**Pull request by jakirkham**
Makes use of `pip check` in testing to ensure dependencies are up-to-date. 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by kmpaul — APPROVED** [review]
Thanks, @jakirkham!

**Comment by kmpaul** [comment]
@jakirkham:  Do you happen to know how to trigger a new conda-forge build from a new PyPI release?  I'm a little mystified about how to enable that ability.  (I realize that might be a non-sequitur.  Sorry!)

**Comment by jakirkham** [comment]
There is a bot that does this periodically via cron job. However there is no way to request that bot to do that work sooner

Another option is to use [Grayskull]( https://github.com/conda-incubator/grayskull ) to update things yourself

**Comment by kmpaul** [comment]
Ok.  So, I don't have to do anything special to enable the bot...?  I'm fine waiting a bit for the bot.

**Comment by jakirkham** [comment]
Yep nothing special needed. Every feedstock is automatically opted in

**Pull request merged**
