### PR TITLE
Add myself to the maintainers list

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Adding myself to the maintainers so I can help out here if necessary

cc @kmpaul

### CODE REVIEW

**Review by kmpaul — APPROVED** [review]
Awesome!  I was going to ask you about that @jacobtomlinson.  Thanks for volunteering.  Do we also need to add you to the CODEOWNERS file?

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render

**Comment by kmpaul** [comment]
You do awesome work, @jakirkham, by the way.  Every time I start wading into something I don't quite fully grasp, you suddenly appear from the shadows and make it all magically work!  Thank you!

**Comment by jakirkham** [comment]
Happy to help 🙂

**Pull request merged**
